### ISSUE TITLE
Class 'Test\UnitTestCase' not found

### ISSUE THREAD

**Issue by bitclaw** [sergeyklay/phalcon-component-example#2]
@sergeyklay 

After doing a git clone and running a composer install , I ran the following command inside the phalcon-component-example directory:

```php vendor/bin/phpunit tests/```

This produces the following error:

```PHP Fatal error:  Class 'Test\UnitTestCase' not found in phalcon-component-example/tests/UnitTest.php```

**Comment by bitclaw** [comment]
@sergeyklay Sorry man layer 8 issue , been doing a lot of front-end work lately and it has been a long time since I've touched PHP :)

Gotta run this command inside the tests folder:

```../vendor/bin/phpunit``` 

Or the other way would be use the -c flag for PHPUnit to load a specific phpunit.xml file.

**Comment by sergeyklay** [comment]
@bitclaw Thank for report. Added docs :)
